### ISSUE TITLE
Fuzzy search

### ISSUE THREAD

**Issue by karniv00l** [TNorbury/command_palette#2]
Hi, 

great package! I will for sure be using it in the future. I did a quick test and thought that I could share my feedback.

It will be nice to have a fuzzy search so the command palette behaves like one in the vscode / sublime / chrome dev tools and others.

Example:

<img width="615" alt="Screenshot 2022-01-21 at 11 16 17" src="https://user-images.githubusercontent.com/3144291/150510319-78ef4ee5-9112-43aa-a30d-c1e1ecffee28.png">

<img width="639" alt="Screenshot 2022-01-21 at 11 16 23" src="https://user-images.githubusercontent.com/3144291/150510399-31fae764-07d7-43df-bf01-c7c5c8a247e0.png">

<img width="640" alt="Screenshot 2022-01-21 at 11 22 29" src="https://user-images.githubusercontent.com/3144291/150510669-be4088ef-e554-4c2b-b2a0-6417d82129e5.png">

I am willing to help. Thanks

**Comment by karniv00l** [comment]
I've just realized that there is an option to use a custom filter

**Comment by karniv00l** [comment]
However, JS package like: https://github.com/timc1/kbar has fuzzy search as a default way of filtering, which for me personally makes more sense. What do you think?

**Comment by TNorbury** [comment]
I think this is a good call, I had initially chosen a basic reg-ex search with an option to customize to give people more control, but after thinking about it over the weekend I think most people want a search/filter that'll work well right out of the box.

I'll take a look at some of the packages available on pub and see if any will get the job done. 
Thanks for the issue!

**Comment by TNorbury** [comment]
Hey @karniv00l, I have a branch `fuzzy_search` that has a basic implementation working. Gonna work on it some more this week to find a score threshold that feels right, as well as get the sub-string highlighting all figured out.

Feel free to check it out!

**Comment by karniv00l** [comment]
That's awesome, thanks!

**Comment by TNorbury** [comment]
@karniv00l Thanks again for the suggestion, I'll have this released later today
