### ISSUE TITLE
Allow to customize or localize instructions

### ISSUE THREAD

**Issue by litterature** [TNorbury/command_palette#38]
We support 3 languages in our app and we would like to show the instructions but to be able to translate the instructions according to the app language.
![image](https://github.com/user-attachments/assets/dee2cdc1-726a-41cb-b27c-ceb724dc8d89)

That would be nice if we could provide our own bottom widget for this.

**Comment by TNorbury** [comment]
Yeah, I can do that. I don't work much with localized apps atm, so I'm not up-to-date on best practices. Would a good solution be adding something like this that would be passed to `CommandPaletteConfig`:
Default options shown, but all of those could be configured.
```dart
CommandPaletteInstructionConfig(
  confirmLabel: "to confirm",
  selectLabel: "to select",
  navigationLabel: "to navigate",
  cancelSelectedLabel: "to cancel selected action",
  closeLabel: "to close",
),
```

Let me know what you think!

**Comment by litterature** [comment]
Hi! This solution would work for us!

**Comment by TNorbury** [comment]
A new version has been published to pub.dev. Version `0.7.6`, it will have the syntax described above with with further addition: `CommandPaletteConfig.showInstructions` has been deprecated in favor of `CommandPaletteInstructionConfig.showInstructions`
