### ISSUE TITLE
Android: Large gap below text input field

### ISSUE THREAD

**Issue by bit-garden** [TNorbury/command_palette#5]
It looks like there is an empty gap on Android. This is with the example provided at https://github.com/TNorbury/command_palette/blob/main/example/lib/main.dart.

This persists in landscape layout as well as with smaller fonts/display settings. 

<img src="https://user-images.githubusercontent.com/10319571/155207805-7a8fe45a-f408-422c-9cc8-d36f426a07bf.png" width=300px>

**Comment by TNorbury** [comment]
Thank you for submitting this issue! I'll take a look at this.

**Comment by TNorbury** [comment]
This has been fixed and pushed to the dev branch. When I fix #6 I'll publish a new release
